module.exports = {
  auth: require("./auth.controller"),
  card: require("./card.controller"),
  message: require("./message.controller"),
  oraculo: require("./oraculo.controller"),
  questionnaire: require("./questionnaire.controller"),
  review: require("././review.controller"),
  service: require("./services.controller"),
  tag: require("./tag.controller"),
  transaction: require("./transaction.controller"),
  upload: require("./uploads.controller"),
  user: require("./user.controller"),
  notification: require("./notification.controller"),
  stripeWebhook: require("./stripe.controller"),
};
