module.exports = {
  Answer: require("./answer.model"),
  Card: require("./card.model"),
  Code: require("./code.model"),
  Message: require("./message.model"),
  Question: require("./question.model"),
  Questionnaire: require("./questionnaire.model"),
  Review: require("./review.model"),
  Service: require("./service.model"),
  Tag: require("./tag.model"),
  Transaction: require("./transaction.model"),
  User: require("./user.model"),
  Notification: require("./notification.model"),
  Payout: require("./payout.model"),
  Payment: require("./payment.model"),
};
